# Generated by Django 5.1.7 on 2025-03-22 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_name'),
        ('authentication', '0002_user_allergy_information_user_current_disease_and_more'),
    ]

    operations = [
    ]
