# Generated by Django 5.1.7 on 2025-03-28 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_merge_20250323_0241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
